//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freedom.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OHLC
    {
        public int Id { get; set; }
        public string Market { get; set; }
        public string Exchange { get; set; }
        public decimal Open { get; set; }
        public decimal High { get; set; }
        public decimal Low { get; set; }
        public decimal Close { get; set; }
        public decimal Volume { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
    }
}
